[package]
name = "privacy_cctp_exit"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.18.0"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true

[profile.release.cairo]
inlining-strategy = 250
